# Generated by Django 5.2.7 on 2025-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('variant', models.CharField(blank=True, max_length=200, null=True)),
                ('pack_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ppg', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sales_value', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('volume_units', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='dashboard_r_year_42bd51_idx'), models.Index(fields=['brand'], name='dashboard_r_brand_8cd1af_idx'), models.Index(fields=['pack_type'], name='dashboard_r_pack_ty_ed6c7a_idx')],
            },
        ),
    ]
